const fs = require("fs");

const secrets = JSON.parse(process.env.INPUT_SECRET_BLOB || "{}");
const vars = JSON.parse(process.env.INPUT_VAR_BLOB || "{}");

const data = `
ANDROID_AD_APP_ID=${secrets.ANDROID_AD_APP_ID}
ANDROID_AD_UNIT_ID=${secrets.ANDROID_AD_UNIT_ID}
IOS_AD_APP_ID=${secrets.IOS_AD_APP_ID}
IOS_AD_UNIT_ID=${secrets.IOS_AD_UNIT_ID}

FIREBASE_PROJECT_NUMBER=${secrets.FIREBASE_PROJECT_NUMBER}
FIREBASE_PROJECT_ID=${secrets.FIREBASE_PROJECT_ID}

FIREBASE_ANDROID_API_KEY=${secrets.FIREBASE_ANDROID_API_KEY}
FIREBASE_ANDROID_APP_ID=${secrets.FIREBASE_ANDROID_APP_ID}

FIREBASE_IOS_API_KEY=${secrets.FIREBASE_IOS_API_KEY}
FIREBASE_IOS_APP_ID=${secrets.FIREBASE_IOS_APP_ID}

FIREBASE_WINDOWS_API_KEY=${secrets.FIREBASE_WINDOWS_API_KEY}
FIREBASE_WINDOWS_APP_ID=${secrets.FIREBASE_WINDOWS_APP_ID}
FIREBASE_WINDOWS_MEASUREMENT_ID=${secrets.FIREBASE_WINDOWS_MEASUREMENT_ID}

FIREBASE_WEB_API_KEY=${secrets.FIREBASE_WEB_API_KEY}
FIREBASE_WEB_APP_ID=${secrets.FIREBASE_WEB_APP_ID}
FIREBASE_WEB_MEASUREMENT_ID=${secrets.FIREBASE_WEB_MEASUREMENT_ID}

LINK_APP_STORE=${vars.LINK_APP_STORE}
LINK_TEST_FLIGHT=${vars.LINK_TEST_FLIGHT}
LINK_GITHUB=https://github.com/${process.env.GITHUB_REPOSITORY}
LINK_GOOGLE_PLAY=${vars.LINK_GOOGLE_PLAY}

UPDATE_FLOWLINE_PERIOD=${secrets.UPDATE_FLOWLINE_PERIOD}
`.trim() + "\n";

fs.writeFileSync(".env", data);

console.log("Generated .env file");
