blank_issues_enabled: false
contact_links:
  - name: Wiki
    url: https://github.com/UnboundTechCo/defyxVPN/wiki
    about: A guide for using the application and troubleshooting issues.
  - name: Privacy policy
    url: https://defyxvpn.com/privacy-policy
    about: The policy for user privacy and data protection.
  - name: Contact us
    url: https://defyxvpn.com/contact
    about: Ways to reach support or the development team.
